/camera_node:
  ros__parameters:
    camera_name: narrow_stereo
    camera_info_url: package://radar_master/config/camera_info.yaml
    frame_id: "camera_optical_frame"
    use_sensor_data_qos: false

    exposure_time: 15000
    gain: 0.0

    offset_x: 0
    offset_y: 0

/orientation_node:
  ros__parameters:
    base: [613, 547,
           872, 780,
           951, 779,
           927, 506]
    
    base_3d: [2795 , 5078, 1556 ,
              -5195, 1772, 615  ,
              -5195, 1112, 615  , 
              12166, 0   , 1106 ]

    region_list: [4,4,4]
    region: [ 7487, 7500,  200,
              2803, 7500,  200,
              2803, 6360,  200,
              7487, 6360,  200,
              6280, 6210,  850,
              4712, 6210,  850,
              4712, 4960,  850,
              6280, 4960,  850,
              820  , 7500,  199,
              -4700, 7500,  199,
              -4700, 6360,  199,
              820  , 6360,  199]

/calibration_ui_node:
  ros__parameters:
    region_list: [4,4,4]

    





