/global_parameter_server:
  ros__parameters:
    model: 0 
    status: 0
    color: 1 #blue0 red1

/camera_1_node:
  ros__parameters:
    camera_name: camera_1
    camera_info_url: package://radar_master/config/camera_info_1.yaml
    topic_name: "image_raw_1"
    frame_id: "camera_1_frame"
    use_sensor_data_qos: true

    exposure_time: 50000
    gain: 10.0

    offset_x: 0
    offset_y: 0

/camera_2_node:
  ros__parameters:
    camera_name: camera_2
    camera_info_url: package://radar_master/config/camera_info_2.yaml
    topic_name: "image_raw_2"
    frame_id: "camera_2_frame"
    use_sensor_data_qos: true

    exposure_time: 50000
    gain: 10.0

    offset_x: 0
    offset_y: 0

/radar_identification_node_1:
  ros__parameters:
    recive_image: "image_raw_1"
    pub_flag: "camera1_flag"
    pub_image: "identification_camera_1"


/radar_identification_node_2:
  ros__parameters:
    recive_image: "image_raw_2"
    pub_flag: "camera2_flag"
    pub_image: "identification_camera_2"


/orientation_node:
  ros__parameters:
    base1: [694,338,
           943,579,
           1024,577,
           1009,304]

    base2: [694,338,
           943,579,
           1024,577,
           1009,304]

    #base_3d: [-5195, 1772, 615 ,
    #          -5195, 1772, 120 ,
    #          -5195, 1112, 120 , 
    #          -5195, 1112, 615 ]

    base_3d: [2795 , 5078, 1556 ,
              -5195, 1772, 615  ,
              -5195, 1112, 615  , 
              12166, 0   , 1106 ]
    
    #base_3d: [ 1000,  1000, 0 ,
    #          -1000,  1000, 0 ,
    #          -1000, -1000, 0 , 
    #           1000, -1000, 0 ]
    
    region_num: 7
    region_list: [4,4,4,4,5,7,7]

    #位置1 对面飞坡起跳处
    #位置2 敌方打符点
    #位置3 己方被飞坡处
    #位置4 己方环形高地 左半
    #位置5 己方环形高地 右半
    #位置6 敌方环形高地 
    #位置7 敌方前哨站下 
    
    region: [ 7487, 7500,  400,
              2803, 7500,  400,
              2803, 6360,  400,
              7487, 6360,  400,

              6280, 6210,  1050,
              4712, 6210,  1050,
              4712, 4960,  1050,
              6280, 4960,  1050,

              820  , 7500,  400,
              -4700, 7500,  400,
              -4700, 6360,  400,
              820  , 6360,  400,

              -1987,  4195,   800,
              -3052,  4941,   800,
              -5045,  2095,   800,
              -3745,  1685,   800,

              -3745,  1685,   800,
              -5045,  2095,   800,
              -5045,  -795,   800,
              -4810, -1131,   800,
              -3745,  -385,   800,

              1987,  -4195,   800,
              3052,  -4941,   800,
              5045,  -2095,   800,
              5045,  795,   800,
              4810, 1131,   800,
              3745,  385,   800,
              3745,  -1685,   800,

              -937,4829,200,
              2144,2672,200,
              2461,2219,200,
              3649,3051,200,
              5238,6360,200,
              -270,6360,200,
              -586,5330,200
              ]
 
/calibration_ui_node:
  ros__parameters:
    region_num: 8
    region_list: [4,4,4,7,4,4,4,7]

    





